name = "WebAssembly Text Format"
grammar = "wat"
path_suffixes = ["wat"]
line_comments = [";; ", ";;; "]
tab_size = 2
autoclose_before = ")"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
      "string",
      "comment",
  ] },
]
word_characters = ["!", "#", "$", "%", "'", "*", "+", "-", ".", "/", ":", "<", "=", ">", "?", "@", "\\", "^", "_", "`", "|", "~"]
